### ISSUE TITLE
DD对象不存在？

### ISSUE THREAD

**Issue by AnsonCode** [guyoung/streakjs#19]
你好，监听该事件时，发现DD对象不存在？
streakjs.DD.drag(evt);

streakjs.DD.endDragBefore(evt);
streakjs.DD.endDragAfter(evt);
```
thirdScriptError
Cannot read property 'endDragBefore' of undefined;at pages/airProcessPro/index page __e function
TypeError: Cannot read property 'endDragBefore' of undefined
    at VueComponent.touchEnd (http://127.0.0.1:25329/appservice/pages/airProcessPro/index.js:272:25)
    at http://127.0.0.1:25329/appservice/common/vendor.js:1322:28
    at Array.forEach (<anonymous>)
    at http://127.0.0.1:25329/appservice/common/vendor.js:1283:19
    at Array.forEach (<anonymous>)
    at ve.handleEvent [as __e] (http://127.0.0.1:25329/appservice/common/vendor.js:1273:13)
    at ve.D (http://127.0.0.1:25329/appservice/__dev__/WAService.js:1:1449641)
    at Ze (http://127.0.0.1:25329/appservice/__dev__/WAService.js:1:1468207)
    at http://127.0.0.1:25329/appservice/__dev__/WAService.js:1:1481030
    at Function.<anonymous> (http://127.0.0.1:25329/appservice/__dev__/WAService.js:1:1481425)
console.error @ VM940:1
errorReport @ VM947 WAService.js:1
thirdErrorReport @ VM947 WAService.js:1
(anonymous) @ VM947 WAService.js:1
D @ VM947 WAService.js:1
Ze @ VM947 WAService.js:1
(anonymous) @ VM947 WAService.js:1
(anonymous) @ VM947 WAService.js:1
(anonymous) @ VM947 WAService.js:1
(anonymous) @ VM947 WAService.js:1
(anonymous) @ VM947 WAService.js:1
i @ VM945 asdebug.js:1
c @ VM945 asdebug.js:1
(anonymous) @ VM945 asdebug.js:1
p @ VM945 asdebug.js:1
f @ VM945 asdebug.js:1
(anonymous) @ VM945 asdebug.js:1
_ws.onmessage @ VM945 asdebug.js:1
```

**Comment by guyoung** [comment]
DD对象不存在问题已修改 @caoyanbin1993
